### PR TITLE
Manpage updates

### PR DESCRIPTION
**Pull request by hughmcmaster**
Hi Nick,

I've gone through all seven manpages and given them a decent rewrite and edit for clarity, consistency, spelling etc.

Please check the changes carefully.

H

### CODE REVIEW

**Comment by lurcher** [comment]
On 14/01/2021 11:22, Hugh McMaster wrote:
>
> Hi Nick,
>
> I've gone through all seven manpages and given them a decent rewrite 
> and edit for clarity, consistency, spelling etc.
>
> Please check the changes carefully.
>
> H
>
Thanks, looks good. I will merge those in latter today.

-- 

Nick

**Comment by hughmcmaster** [comment]
Anything to change here?

**Comment by hughmcmaster** [comment]
Hey Nick, did you want any changes on this docs PR?

**Comment by lurcher** [comment]
On 02/03/2021 04:48, Hugh McMaster wrote:
>
> Hey Nick, did you want any changes on this docs PR?
>

Yep, though I am useless at that.

**Comment by hughmcmaster** [comment]
Okay. I think you can merge changes into the branch as separate commits. Or use github's review function on the relevant lines and I can update the patches.

**Pull request merged**
