### PR TITLE
isql.1: Add information about handling passwords containing semicolons

### PR DESCRIPTION
**Pull request by hughmcmaster**
Closes: #113

### CODE REVIEW

**Comment by hughmcmaster** [comment]
Hi Nick, any concerns with this man page update?

**Comment by lurcher** [comment]
On 10/01/2023 22:55, Hugh McMaster wrote:
>
> Hi Nick, any concerns with this man page update?
>
Not done yet, will get to it.

**Comment by hughmcmaster** [comment]
I've just rebased this pull request, since you made some changes a while ago.

**Comment by hughmcmaster** [comment]
Bump :)

**Review by lurcher — APPROVED** [review]

**Pull request merged**
